production:
  bucket: "apelian-prod"
  access_key_id: "AKIAINBCXC7Y4PANEJOQ"
  secret_access_key: "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"
development:
  bucket: "apelian-prod"
  access_key_id: "AKIAINBCXC7Y4PANEJOQ"
  secret_access_key: "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"
test:
  bucket: "apelian-test"
  access_key_id: "AKIAINBCXC7Y4PANEJOQ"
  secret_access_key: "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"
